name: ALog
options:
  useBaseInternationalization: false
  enableBaseInternationalization: false
  groupOrdering:
    - order: [Sources, Resources, Shared]
settings:
  MARKETING_VERSION: 0.0.5
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
  CODE_SIGN_STYLE: Manual
  CURRENT_PROJECT_VERSION: 1
  VERSIONING_SYSTEM: apple-generic
  DEVELOPMENT_TEAM: ZTQ4TGAKFX
packages:
  XLog:
    path: ./Packages/XLog
  XLang:
    path: ./Packages/XLang
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    from: 4.2.0
  ConfettiSwiftUI:
    url: https://github.com/simibac/ConfettiSwiftUI.git
    from: 1.1.0
  ArkanaKeys:
    path: ./ArkanaKeys/ArkanaKeys
  ArkanaKeysInterfaces:
    path: ./ArkanaKeys/ArkanaKeysInterfaces
configs:
  Debug: debug
  Snapshot: debug
  AppStore: release
schemes:
  ALog:
    build:
      targets:
        ALog: all
      config: Debug
    test:
      targets:
        - name: ALogTests
    run:
      config: Debug
      commandLineArguments:
        "-com.apple.CoreData.ConcurrencyDebug 1": true
        "-com.apple.CoreData.SQLDebug 1": true
  ALogWatch:
    build:
      targets:
        ALogWatch: all
      config: Debug
    run:
      config: Debug
  SnapshotTests:
    build:
      targets:
        SnapshotTests: test
    test:
      targets:
        - SnapshotTests
      config: Snapshot
targets:
  ALogWatch:
    type: application
    platform: watchOS
    deploymentTarget: "9.0"
    dependencies:
      - package: XLog
      - package: XLang
      - target: ALogWatchWidget
    sources:
      - Watch
      - Shared
    info:
      path: Watch/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        WKCompanionAppBundleIdentifier: app.tarbo.memo
        NSMicrophoneUsageDescription: "ALog requires access to your microphone."
        UIBackgroundModes: [audio]
    settings:
      base: 
        PRODUCT_BUNDLE_IDENTIFIER: app.tarbo.memo.watch
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: true
      configs:
        Debug:
          PROVISIONING_PROFILE_SPECIFIER: match Development app.tarbo.memo.watch
          CODE_SIGN_IDENTITY: iPhone Developer
        AppStore:
          PROVISIONING_PROFILE_SPECIFIER: match AppStore app.tarbo.memo.watch
          CODE_SIGN_IDENTITY: iPhone Distribution
  ALogWatchWidget:
    type: app-extension
    platform: watchOS
    deploymentTarget: "9.0"
    sources:
      - WatchWidget
    info:
      path: WatchWidget/Info.plist
      properties:
        CFBundleDisplayName: ALog
        CFBundleShortVersionString: $(MARKETING_VERSION)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
    settings:
      base: 
        PRODUCT_BUNDLE_IDENTIFIER: app.tarbo.memo.watch.widget
        GENERATE_INFOPLIST_FILE: true
      configs:
        Debug:
          PROVISIONING_PROFILE_SPECIFIER: match Development app.tarbo.memo.watch.widget
          CODE_SIGN_IDENTITY: iPhone Developer
        AppStore:
          PROVISIONING_PROFILE_SPECIFIER: match AppStore app.tarbo.memo.watch.widget
          CODE_SIGN_IDENTITY: iPhone Distribution
  ALogTests:
    type: bundle.unit-test
    platform: iOS
    path: Tests/Info.plist
    sources:
      - Tests
    dependencies:
      - target: ALog
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        PRODUCT_BUNDLE_IDENTIFIER: app.tarbo.memo.tests
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_MACCATALYST: NO
  ALogWidget:
    type: app-extension
    platform: iOS
    sources:
      - WatchWidget
    info:
      path: WatchWidget/Info.plist
      properties:
        CFBundleDisplayName: ALog
        CFBundleShortVersionString: $(MARKETING_VERSION)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
    settings:
      base: 
        PRODUCT_BUNDLE_IDENTIFIER: app.tarbo.memo.widget
        GENERATE_INFOPLIST_FILE: true
        SKIP_INSTALL: true
      configs:
        Debug:
          PROVISIONING_PROFILE_SPECIFIER: match Development app.tarbo.memo.widget
          CODE_SIGN_IDENTITY: iPhone Developer
        AppStore:
          PROVISIONING_PROFILE_SPECIFIER: match AppStore app.tarbo.memo.widget
          CODE_SIGN_IDENTITY: iPhone Distribution
  ALog:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    dependencies:
      - package: XLog
      - package: XLang
      - package: KeychainAccess
      - package: ArkanaKeys
      - package: ArkanaKeysInterfaces
      - package: ConfettiSwiftUI
      - target: ALogWatch
      - target: ALogWidget
    sources:
      - Sources
      - Resources
      - Shared
    info:
      path: Resources/Info.plist
      properties:
        NSHumanReadableCopyright: Copyright © 2023 Tarbo Tech, LLC
        CFBundleShortVersionString: $(MARKETING_VERSION)
        AppStoreURL: https://apps.apple.com/us/app/alog/id6451082482
        GIT_HASH: "${GIT_HASH}"
        RELEASE_DATE: "20230810"
        UILaunchStoryboardName: Launch Screen
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        ITSAppUsesNonExemptEncryption: false
        NSSpeechRecognitionUsageDescription: "Access to speech recognition functionality is required."
        NSMicrophoneUsageDescription: "ALog requires access to your microphone so that you can record entries in your journal."
        UIBackgroundModes: [audio]
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        PRODUCT_BUNDLE_IDENTIFIER: app.tarbo.memo
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      configs:
        Debug:
          PROVISIONING_PROFILE_SPECIFIER: match Development app.tarbo.memo
          CODE_SIGN_IDENTITY: iPhone Developer
        AppStore:
          PROVISIONING_PROFILE_SPECIFIER: match AppStore app.tarbo.memo
          CODE_SIGN_IDENTITY: iPhone Distribution
        Snapshot:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: [DEBUG, SNAPSHOT]
  SnapshotTests:
    type: bundle.ui-testing
    platform: iOS
    sources: [SnapshotTests]
    dependencies:
      - target: ALog
    settings:
      INFOPLIST_FILE: Resources/Info.plist
