/** Generated by l10n */

public enum MyLocalizedKey: String {
  /**应用名称*/
  case app_name = "app_name"
  /**评价*/
  case review_app = "review_app"
  /**评分*/
  case rate_on_the_app_store = "rate_on_the_app_store"
  /**分享给朋友*/
  case share_with_friends = "share_with_friends"
  /**关于*/
  case about_app = "about_app"
  /**公司*/
  case company = "company"
  /**Done*/
  case done = "done"
  /**Cancel*/
  case cancel = "cancel"
  /**Next*/
  case next = "next"
  /**Error*/
  case error = "error"
  /**Delete*/
  case delete = "delete"
  /**Edit*/
  case edit = "edit"
  /**OK*/
  case ok = "ok"
  /**Enable 开关*/
  case enable = "enable"
  /**Copy*/
  case copy = "copy"
  /**Memo*/
  case memo = "memo"
  /**Save*/
  case save = "save"
  /**API Key*/
  case api_key = "api_key"
  /**Verify*/
  case verify = "verify"
  /**Version*/
  case version = "version"
  /**关于*/
  case about = "about"
  /**Recording*/
  case recording = "recording"
  /**确认对话框*/
  case are_you_sure = "are_you_sure"
  /**分享*/
  case share = "share"
  /**分享音频*/
  case share_audio = "share_audio"
  /**预览*/
  case preview = "preview"
  /**可选*/
  case optional = "optional"
  /**总结*/
  case summarize = "summarize"
  /**重新总结*/
  case resummarize = "resummarize"
  /**转写*/
  case transcribe = "transcribe"
  /**重新转写*/
  case retranscribe = "retranscribe"
  /**导出*/
  case export = "export"
  /**Try Again*/
  case try_again = "try_again"
  /**Privacy Policy*/
  case privacy_policy = "privacy_policy"
  /**Terms of Use*/
  case terms_of_use = "terms_of_use"
  /**Source Code*/
  case source_code = "source_code"
  /**Not Now*/
  case not_now = "not_now"
  /**Unlimited*/
  case unlimited = "unlimited"
  /**Characters*/
  case characters = "characters"
  /**Default*/
  case _default = "_default"
  /**无效自定义服务器*/
  case error_invalid_custom_server = "error_invalid_custom_server"
  /**外观 - 自动*/
  case dark_mode_auto = "dark_mode_auto"
  /**外观 - 浅色*/
  case dark_mode_light = "dark_mode_light"
  /**外观 - 深色*/
  case dark_mode_dark = "dark_mode_dark"
  /**服务器 - 默认*/
  case server_default = "server_default"
  /**服务器 - 自定义*/
  case server_custom = "server_custom"
  /**Premium*/
  case premium = "premium"
  /**一次性付费升级*/
  case premium_one_time_upgrade = "premium_one_time_upgrade"
  /**感谢升级*/
  case premium_thanks = "premium_thanks"
  /**恢复购买*/
  case premium_restore_purchase = "premium_restore_purchase"
  /**总结数量*/
  case premium_summary_num = "premium_summary_num"
  /**提示词数量*/
  case premium_prompt_num = "premium_prompt_num"
  /**自定义服务器*/
  case premium_custom_server = "premium_custom_server"
  /**导出数据*/
  case premium_export_data = "premium_export_data"
  /**每日字符上限*/
  case premium_daily_character_limit = "premium_daily_character_limit"
  /**购买按钮 - 展示价格*/
  case premium_go_premium = "premium_go_premium"
  /**升级到高级版*/
  case premium_upgrade_to_premium = "premium_upgrade_to_premium"
  /**申请权限 - 标题*/
  case permission_mic_title = "permission_mic_title"
  /**申请权限 - 正文*/
  case permission_mic_msg = "permission_mic_msg"
  /**申请权限 - 正文 (denied)*/
  case permission_mic_denied_msg = "permission_mic_denied_msg"
  /**申请权限 - 以后再说*/
  case permission_not_now = "permission_not_now"
  /**申请权限 - 允许*/
  case permission_allow = "permission_allow"
  /**申请权限 - 打开设置*/
  case permission_open_settings = "permission_open_settings"
  /**设置标题*/
  case settings_title = "settings_title"
  /**设置 - 通用*/
  case settings_general = "settings_general"
  /**设置 - 新一天开始时间*/
  case settings_day_starts_at = "settings_day_starts_at"
  /**设置 - 应用语言*/
  case settings_app_language = "settings_app_language"
  /**设置 - 外观*/
  case settings_app_appearance = "settings_app_appearance"
  /**设置 - 录音结束自动保存*/
  case settings_auto_save = "settings_auto_save"
  /**设置 - 服务器*/
  case settings_server = "settings_server"
  /**设置 - 自定义服务器设置*/
  case settings_server_settings = "settings_server_settings"
  /**设置 - 自定义服务器 - 主机*/
  case settings_server_host = "settings_server_host"
  /**设置 - 自定义服务器 - 需要 API KEY*/
  case settings_server_requires_key = "settings_server_requires_key"
  /**设置 - 自定义服务器 - 验证 chat api*/
  case settings_server_verify_item_chat = "settings_server_verify_item_chat"
  /**设置 - 自定义服务器 - 验证 whisper*/
  case settings_server_verify_item_whisper = "settings_server_verify_item_whisper"
  /**设置 - 转写*/
  case settings_trans = "settings_trans"
  /**设置 - 转写 - 语言*/
  case settings_trans_lang = "settings_trans_lang"
  /**设置 - 转写 - 服务*/
  case settings_trans_provider = "settings_trans_provider"
  /**设置 - 转写 - 隐私警告*/
  case settings_trans_privacy_warning = "settings_trans_privacy_warning"
  /**设置 - 总结*/
  case settings_sum = "settings_sum"
  /**设置 - 总结 - 服务*/
  case settings_sum_provider = "settings_sum_provider"
  /**设置 - 总结 - AI 模型*/
  case settings_sum_ai_model = "settings_sum_ai_model"
  /**设置 - 总结 - 提示词*/
  case settings_sum_prompts = "settings_sum_prompts"
  /**设置 - 总结 - add prompt*/
  case settings_sum_prompts_add = "settings_sum_prompts_add"
  /**设置 - 总结 - Edit prompt*/
  case settings_sum_prompts_edit = "settings_sum_prompts_edit"
  /**导出数据*/
  case export_data = "export_data"
  /**导出数据 - 类别*/
  case export_category = "export_category"
  /**导出数据 - 类别 - 笔记*/
  case export_category_note = "export_category_note"
  /**导出数据 - 类别 - 总结*/
  case export_category_summary = "export_category_summary"
  /**导出数据 - 格式*/
  case export_format = "export_format"
  /**Timeline*/
  case timeline = "timeline"
  /**Timeline - "no entries"*/
  case timeline_empty = "timeline_empty"
  /**Timeline - 录音按钮 - "tap here"*/
  case timeline_recbtn_tap_here = "timeline_recbtn_tap_here"
  /**Summary*/
  case summary = "summary"
  /**Summary - "no summaries"*/
  case summary_empty = "summary_empty"
  /**转写 - Apple*/
  case trans_provider_apple = "trans_provider_apple"
  /**转写 - OpenAI (Whisper)*/
  case trans_provider_openai = "trans_provider_openai"
  /**转写 - Apple - 提示*/
  case trans_provider_apple_notice = "trans_provider_apple_notice"
  /**转写 - Whisper - 提示*/
  case trans_provider_openai_notice = "trans_provider_openai_notice"
  /**转写 - 正在转写*/
  case transcribing = "transcribing"
  /**转写 - 语言 - 自动检测*/
  case trans_lang_auto = "trans_lang_auto"
  /**英语*/
  case trans_lang_en = "trans_lang_en"
  /**日语*/
  case trans_lang_ja = "trans_lang_ja"
  /**简体中文*/
  case trans_lang_zh_hans = "trans_lang_zh_hans"
  /**总结 - 标题*/
  case sum_title = "sum_title"
  /**总结 - 默认标题*/
  case sum_title_default = "sum_title_default"
  /**总结 - 没有提示词*/
  case sum_no_prompts = "sum_no_prompts"
  /**总结 - 选择提示词*/
  case sum_choose_prompt = "sum_choose_prompt"
  /**总结 - 添加提示词按钮*/
  case sum_add_prompt = "sum_add_prompt"
  /**总结 - 字数不够*/
  case sum_text_too_short = "sum_text_too_short"
  /**总结 - 选择日记 - 标题*/
  case sum_select_memos_title = "sum_select_memos_title"
  /**提示词*/
  case prompt = "prompt"
  /**提示词 - title*/
  case prompt_title = "prompt_title"
  /**提示词 - 描述*/
  case prompt_desc = "prompt_desc"
  /**提示词 - 温度*/
  case prompt_temperature = "prompt_temperature"
  /**提示词 - 温度参数描述*/
  case prompt_temperature_desc = "prompt_temperature_desc"
  /**提示词 - content*/
  case prompt_content = "prompt_content"
  /**提示词 - 模版*/
  case prompt_content_template = "prompt_content_template"
  /**Credits - 一口新饭*/
  case credit_onenewbite_name = "credit_onenewbite_name"
  /**Credits - 一口新饭 - url*/
  case credit_onenewbite_url = "credit_onenewbite_url"
  /**Credits - goldengrape*/
  case credit_goldengrape_name = "credit_goldengrape_name"
  /**Credits - goldengrape - url*/
  case credit_goldengrape_url = "credit_goldengrape_url"
  /**Watch - 没有权限 - 标题*/
  case watch_permission_title = "watch_permission_title"
  /**Watch - 没有权限 - 内容*/
  case watch_permission_msg = "watch_permission_msg"
  /**Watch - 最近录音*/
  case watch_recents = "watch_recents"
  /**Watch - 没有录音*/
  case watch_recents_empty = "watch_recents_empty"
}