devices([
 "iPhone 15 Pro Max",
 "iPhone 15 Plus",
 "iPhone 8 Plus",
 "iPad Pro (12.9-inch) (6th generation)",
 "iPad Pro (12.9-inch) (2nd generation)",
])

languages([
  "en-US",
  "zh-Hans"
])

scheme "SnapshotTests"

