/** Generated by l10n */

public enum MyLocalizedKey: String {
  /**应用名称*/
  case app_name = "app_name"
  /**评价*/
  case review_app = "review_app"
  /**分享*/
  case share_app = "share_app"
  /**关于*/
  case about_app = "about_app"
  /**公司*/
  case company = "company"
  /**Done*/
  case done = "done"
  /**Cancel*/
  case cancel = "cancel"
  /**Next*/
  case next = "next"
  /**Error*/
  case error = "error"
  /**Delete*/
  case delete = "delete"
  /**Edit*/
  case edit = "edit"
  /**OK*/
  case ok = "ok"
  /**Enable*/
  case enable = "enable"
  /**Copy*/
  case copy = "copy"
  /**Paste*/
  case paste = "paste"
  /**Memo*/
  case memo = "memo"
  /**Save*/
  case save = "save"
  /**API Key*/
  case api_key = "api_key"
  /**Verify*/
  case verify = "verify"
  /**Version*/
  case version = "version"
  /**关于*/
  case about = "about"
  /**Recording*/
  case recording = "recording"
  /**确认对话框*/
  case are_you_sure = "are_you_sure"
  /**分享*/
  case share = "share"
  /**分享音频*/
  case share_audio = "share_audio"
  /**预览*/
  case preview = "preview"
  /**可选*/
  case optional = "optional"
  /**总结*/
  case summarize = "summarize"
  /**Try Again*/
  case try_again = "try_again"
  /**Privacy Policy*/
  case privacy_policy = "privacy_policy"
  /**Terms of Use*/
  case terms_of_use = "terms_of_use"
  /**Source Code*/
  case source_code = "source_code"
  /**申请权限 - 标题*/
  case permission_mic_title = "permission_mic_title"
  /**申请权限 - 正文*/
  case permission_mic_msg = "permission_mic_msg"
  /**申请权限 - 正文 (denied)*/
  case permission_mic_denied_msg = "permission_mic_denied_msg"
  /**申请权限 - 以后再说*/
  case permission_not_now = "permission_not_now"
  /**申请权限 - 允许*/
  case permission_allow = "permission_allow"
  /**申请权限 - 打开设置*/
  case permission_open_settings = "permission_open_settings"
  /**设置标题*/
  case settings_title = "settings_title"
  /**设置 - 通用*/
  case settings_general = "settings_general"
  /**设置 - 新一天开始时间*/
  case settings_day_starts_at = "settings_day_starts_at"
  /**设置 - openai*/
  case settings_openai = "settings_openai"
  /**设置 - openai - 设置*/
  case settings_openai_settings = "settings_openai_settings"
  /**设置 - openai - 设置 - key 获取方式*/
  case settings_openai_settings_key_method = "settings_openai_settings_key_method"
  /**设置 - 转写*/
  case settings_trans = "settings_trans"
  /**设置 - 转写 - 语言*/
  case settings_trans_lang = "settings_trans_lang"
  /**设置 - 转写 - 服务*/
  case settings_trans_provider = "settings_trans_provider"
  /**设置 - 转写 - 隐私警告*/
  case settings_trans_privacy_warning = "settings_trans_privacy_warning"
  /**设置 - 总结*/
  case settings_sum = "settings_sum"
  /**设置 - 总结 - 服务*/
  case settings_sum_provider = "settings_sum_provider"
  /**设置 - 总结 - AI 模型*/
  case settings_sum_ai_model = "settings_sum_ai_model"
  /**设置 - 总结 - 提示词*/
  case settings_sum_prompts = "settings_sum_prompts"
  /**设置 - 总结 - add prompt*/
  case settings_sum_prompts_add = "settings_sum_prompts_add"
  /**设置 - 总结 - Edit prompt*/
  case settings_sum_prompts_edit = "settings_sum_prompts_edit"
  /**Timeline*/
  case timeline = "timeline"
  /**Timeline - "no entries"*/
  case timeline_empty = "timeline_empty"
  /**Timeline - 录音按钮 - "tap here"*/
  case timeline_recbtn_tap_here = "timeline_recbtn_tap_here"
  /**Summary*/
  case summary = "summary"
  /**Summary - "no summaries"*/
  case summary_empty = "summary_empty"
  /**转写 - Apple*/
  case trans_provider_apple = "trans_provider_apple"
  /**转写 - OpenAI (Whisper)*/
  case trans_provider_openai = "trans_provider_openai"
  /**转写 - Apple - 提示*/
  case trans_provider_apple_notice = "trans_provider_apple_notice"
  /**转写 - OpenAI - API KEY 警告*/
  case trans_provider_opanai_api_key_warning = "trans_provider_opanai_api_key_warning"
  /**转写 - 正在转写*/
  case transcribing = "transcribing"
  /**转写 - 语言 - 自动检测*/
  case trans_lang_auto = "trans_lang_auto"
  /**英语*/
  case trans_lang_en = "trans_lang_en"
  /**日语*/
  case trans_lang_ja = "trans_lang_ja"
  /**简体中文*/
  case trans_lang_zh_hans = "trans_lang_zh_hans"
  /**总结 - OpenAI*/
  case sum_service_openai = "sum_service_openai"
  /**总结 - OpenAI - API KEY 警告*/
  case sum_opanai_api_key_warning = "sum_opanai_api_key_warning"
  /**总结 - 标题*/
  case sum_title = "sum_title"
  /**总结 - 默认标题*/
  case sum_title_default = "sum_title_default"
  /**总结 - 没有提示词*/
  case sum_no_prompts = "sum_no_prompts"
  /**总结 - 选择提示词*/
  case sum_choose_prompt = "sum_choose_prompt"
  /**总结 - 添加提示词按钮*/
  case sum_add_prompt = "sum_add_prompt"
  /**总结 - 字数不够*/
  case sum_text_too_short = "sum_text_too_short"
  /**提示词*/
  case prompt = "prompt"
  /**提示词 - title*/
  case prompt_title = "prompt_title"
  /**提示词 - 描述*/
  case prompt_desc = "prompt_desc"
  /**提示词 - content*/
  case prompt_content = "prompt_content"
  /**提示词 - 模版*/
  case prompt_content_template = "prompt_content_template"
  /**Credits - 一口新饭*/
  case credit_onenewbite_name = "credit_onenewbite_name"
  /**Credits - 一口新饭 - 描述*/
  case credit_onenewbite_desc = "credit_onenewbite_desc"
  /**Credits - 一口新饭 - url*/
  case credit_onenewbite_url = "credit_onenewbite_url"
}